// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/10/2026, 7:20:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/runner/workspace/artifacts/payment-portal/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/artifacts/payment-portal/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/artifacts/payment-portal/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/artifacts/payment-portal/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/artifacts/payment-portal/plugins/**/*.{js,ts,mjs}","/home/runner/workspace/artifacts/payment-portal/composables/**/*.{js,ts,mjs}","/home/runner/workspace/artifacts/payment-portal/utils/**/*.{js,ts,mjs}","/home/runner/workspace/artifacts/payment-portal/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/artifacts/payment-portal/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/artifacts/payment-portal/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/artifacts/payment-portal/app.config.{js,ts,mjs}","/home/runner/workspace/artifacts/payment-portal/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;